[package]
name = "ble-metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11"
tokio = { version = "1", features = ["full"] }
uuid = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
