apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
      - name: app
        image: pechka-app:latest
        args: ["catalog-service"]
        env:
        - name: PORT
          value: "8082"
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
  - port: 8082
    targetPort: 8082
