apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
spec:
  template:
    spec:
      containers:
      - name: mc
        image: minio/mc
        command:
        - /bin/sh
        - -c
        - |
          until (/usr/bin/mc alias set myminio http://minio:9000 admin password123) do echo '...waiting...' && sleep 1; done;
          /usr/bin/mc mb myminio/assets || true;
          /usr/bin/mc anonymous set public myminio/assets;
          exit 0;
      restartPolicy: OnFailure
  backoffLimit: 10
