apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: pechka
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim: null
          emptyDir: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: pechka
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim: null
          emptyDir: {}
