apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pechka-ingress-public
  namespace: pechka
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - pechka.wpcapp.net
        - pechka-workflow.wpcapp.net
      secretName: wpcapp-net-wildcard-tls
  rules:
    - host: pechka.wpcapp.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
    - host: pechka-workflow.wpcapp.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-server
                port:
                  number: 2746
