apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pechka-ingress
  namespace: pechka
spec:
  rules:
    - host: pechka.nuage.cluster.wpc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
