apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-bluray-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadOnlyMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadOnlyMany
