apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  DB_HOST: <path:secrets/prod-postgres.yaml#DB_HOST>
  DB_NAME: <path:secrets/prod-postgres.yaml#DB_NAME>
  DB_USER: <path:secrets/prod-postgres.yaml#DB_USER>
  DB_PASSWORD: <path:secrets/prod-postgres.yaml#DB_PASSWORD>
  DB_PORT: "5432"
