apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_URL: "postgres://postgres:password@db:5432/streaming_db?sslmode=disable"
  MONGODB_URI: "mongodb://mongodb:27017"
  MONGODB_DB: "streaming_catalog"
  REDIS_URL: "redis:6379"
  MINIO_ENDPOINT: "http://minio:9000"
  MINIO_BUCKET: "assets"
  CDN_BASE_URL: "/assets"
  NFS_SCAN_PATH: "/mnt/nfs"
  THUMBNAIL_ANALYZER_URL: "http://thumbnail-analyzer:8000"
  CATALOG_SERVICE_URL: "http://catalog-service:8082"
  JWT_ACCESS_TTL_MINUTES: "15"
  JWT_REFRESH_TTL_DAYS: "30"
  PYTHONUNBUFFERED: "1"
  NEXT_PUBLIC_API_URL: "http://localhost:8000"
  INTERNAL_API_URL: "http://nginx:80"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
