resources:
- sync-checkpoint-pvc.yaml
- sync-deployment.yaml
- nfs-importer.yaml
- analyzer.yaml

configMapGenerator:
- name: benthos-config
  files:
    - benthos/resources/shared.yaml
    - benthos/streams/contents.yaml
