apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-batch
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app
            image: pechka-app:latest
            args: ["sync-batch"]
            envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          restartPolicy: OnFailure
