apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-bluray-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-readonly-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
