apiVersion: v1
kind: Pod
metadata:
  name: etl-importer
  namespace: pechka
  labels:
    app: etl-importer
spec:
  containers:
    - name: importer
      image: alpine:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: bluray-volume
          mountPath: /mnt/bluray
        - name: hls-volume
          mountPath: /mnt/hls
  volumes:
    - name: bluray-volume
      persistentVolumeClaim:
        claimName: nfs-bluray-pvc
    - name: hls-volume
      persistentVolumeClaim:
        claimName: nfs-hls-pvc
  restartPolicy: Always
