resources:
  - ../../base
  - postgres
  - minio
  - secrets.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pechka-config
    namespace: pechka
    literals:
      - minio-bucket=pechka
      - minio-url=minio:9000

