resources:
  - ../../base
  - postgres
  - minio
  - secrets.yaml

patches:
  - path: image-pull-policy-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: pechka-config
    namespace: pechka
    literals:
      - minio-bucket=pechka
      - minio-url=minio:9000
      - allowed-ip-range=0.0.0.0/0
