resources:
  - ../../base
  - postgres
  - minio
  - secrets.yaml

patches:
  - path: image-pull-policy-patch.yaml
  - path: postgres/migrate-job-patch.yaml

generatorOptions:
  disableNameSuffixHash: true
