MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:PUkG+JE3LX8b,iv:TEFzz8JlDu2Ea9VuNtNGFsXFr3XhgSB4cFf9ofXikng=,tag:X3Et4iMjovwzEQRsS45k1g==,type:str]
MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:uq8uhak6prjE1RBCnYDKZEgpdg==,iv:k4/WP2toLLU6tBCjvsoBpeFv+FVl7cmObNsTvZdR0fo=,tag:ivST8TFEy9Nb6SysjZ5yBQ==,type:str]
MONGO_INITDB_DATABASE: ENC[AES256_GCM,data:SH5LkPp3,iv:cFlrAuvAmHs6bCHArhl4TW5kXiKxQJMw7e2PSCqMfmo=,tag:HJ+qlu+LzyK4Uo9kMQLGlg==,type:str]
MINIO_ROOT_USER: ENC[AES256_GCM,data:2+wWSnkfw6Qox6vSvbIrcPQ=,iv:boiNo9npw/d3Epocq+cw3wySwsng2IaPRyOckUhevlg=,tag:54ZFhCiggVSn4HaW3ppKHQ==,type:str]
MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:5MxZD5pUcpAvKZHxL7/mo3UA9g==,iv:CWyZeEV9etc903UAOaT2y8OsNhMOEVp/Yd0HECFKffc=,tag:s+ubUamA6moTXk6qpq49gg==,type:str]
DB_NAME: ENC[AES256_GCM,data:5UI8OWjI,iv:ABnGSGjtD8u57Z+eRJofC6v7tpdEoaG8D37w5ieptSo=,tag:9ikALXEb0OCWQE3nEG1Few==,type:str]
DB_USER: ENC[AES256_GCM,data:lUmmhfLswQp5crWMCPIO,iv:WryzDt1z/5rmhbYURpy5GXk75THTILvS8bM3h6uK3/o=,tag:57FXS4axn0z8pBCoUVvQFQ==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:lx1ik53r/eZzJSB+e31/Ow==,iv:sAQkoFbUtiQEUbP/Oaj78rZpM5Bu04FvC/eE1ojQovc=,tag:yHLP9MQRYLPRYx1m3LuJHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVGtnVjVZUEJUS1hZOG9m
            Vlp5TU9PUi8xaWhPZUZMKytHQ3A0QlZTVFJJCkZCVEFvYzlvOEVXdDVSQUlMcmRu
            ZHYwU2ZrM1ZsWjdTNnZMOEd6VWgwV1EKLS0tIElPZWNidnpoOGlxOTJJeVpLTk5F
            RS9yVUJmTXMzV0dteEFhcjJYUUJrNEUKWzKraglY9hmUVKXXTZg2K5z/WXMwIJBA
            zrshzRRXZYYZ7GMeBFfjeLI3xEfHR0053KhikYdlo8g+KVVLsT/GKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqgm0gczrwyluk9lyhpz49uea7m04u53q4c60kwn9s6wuguhju3qjznrut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcXpEVHF4MGRaVHZ1UnRx
            UGcyKzVhQm1IV1ZNajdKeTNXelJXbktuWGlJCkFnUHNXayszejZNc1o5djFlK2lM
            ZW5WYTdyNlZ4MjlsWkFNeXROcmZNRjgKLS0tIFJSUFA2TFF2L242ZFFsWEFpcThE
            TjB6ekR4L3RWR2o2UjlBdWQ4S3Z6UlUKvDbsvUjYzGaS4u/QAUQl3Ogm2KQ6ZWNU
            gqePqIIZKBhljdDCb6Go2KoaIF9R5qNpELAJIWhDrrmnhPvGpJ3WSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-22T09:24:21Z"
    mac: ENC[AES256_GCM,data:5JE6DI9QAR7ppj7KVe7ytxKQhrDqHa3Rcbq2leivaFA7pvrGIGu5sIzi5MCjjZEja0yj36vULFgAr2Du81fJzdB8M26QfOCJVLVL3wA6Pu2H26gY/v6Wqt4iJKIC+SgiwZNyqyv/iryAYZgOW+rkURC4dbpF+q6H/4lj6jK3Y80=,iv:zhsmDFhjhMkcq124ERjsBFkW+0VUqybU8uMiCoqiOE0=,tag:CQpco42MqNWoPetpHfU98A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
