DB_HOST: ENC[AES256_GCM,data:iADIJ8o0nKjioULx,iv:kEJW7GYIjyP73f7S9MxxedQiMFmZWq53iDfv8Ir5qEg=,tag:zwjtpviCqszHFdnplht0VQ==,type:str]
DB_NAME: ENC[AES256_GCM,data:/wClS11z9YrpKjCY,iv:1L74B8OcUahEqjOpbCOptQxOw2KmEnG+/TRBjMSbyFc=,tag:VG05qDNnWJy8WCB6twKupg==,type:str]
DB_USER: ENC[AES256_GCM,data:A0ShDddA+Q==,iv:YkmuZJcuaACBLo4AhKZj5hp1Q4XcxxypmticmxnKa1c=,tag:mr74woU9PEiESb8PGEfSmA==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:7zv+wWHmE+rB7Fxn9oritd5n6yoK,iv:AwmFMrK37qemyUpjXcO3mtA0Cf9ROeGotVzIojBo0Ho=,tag:XJGjVT8mfpbULZfDrVx0qQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZytvMFJvb2xjZ1A0T0k0
            YTVrVWF6UnlNTS8rVVl6dnZodjZ6QkV1WFJFCkNOS3A5L2sxbHFwb1dkdXFZeTlJ
            UkxjaXdUcWdhQWlHS21HUFFCUk9scVUKLS0tIGRUdEVwSTJ0VFNKZ2FnT0pmMnY2
            dENlRmczMzQwMzV0cnRVajhJQS9iRWcKF0MwQBCvEhQGKVonXnTPyUdphLWkkx+/
            sSLnxEoswAix4NF9RULf3Kt3HojdxDcm34Dn6PePdUDD9fFOTyoxIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqgm0gczrwyluk9lyhpz49uea7m04u53q4c60kwn9s6wuguhju3qjznrut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZStvcTdFV21JRkJpdnNr
            Unl2eHNNMTRqZTZtUnhXOU8vbkNVTVF1RkNvCmZ2UVF5bGtFOWdFVDhXdjhkYWtU
            MXhRVG0zY0Q4UlFITmY0S2pidVNOdUUKLS0tIG45YkN2bWtQeHVXRms4VmdJUzdi
            am5Rc2ErUnIxM0FLV1lkV2ljZlk5d1EK1q9GT6e3VXLS6NKSHkKM1kfCNg5HnqX8
            JdCFdu8lxhiFvQAKHd3jImKfjHQTrZ/EDOcfZnL94Oy+O1yjFhn1/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T11:02:45Z"
    mac: ENC[AES256_GCM,data:wLuCJMoRTKt6ZyJHdbLWMT5XFyp0pgRgnEu7PHCxJP4GE/k7LR/R6WJoxP3315HFovI3YRkd4FnA5PFH/JbmqdbwS/0ttSRjUeBDp9xQhbNERfgtbLgZAKTFz9LN4Mc24a9t2NLTVmaRW/7AunXJeB4UfT7rZTaewq3RJv6Iqfw=,iv:CCjV8OJLqeT++J9OCh+1b6Ikk8inSV1R4sVS8rPLkBc=,tag:J0rYsU34pV25n3+yHBgP0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
