MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:PUkG+JE3LX8b,iv:TEFzz8JlDu2Ea9VuNtNGFsXFr3XhgSB4cFf9ofXikng=,tag:X3Et4iMjovwzEQRsS45k1g==,type:str]
MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:uq8uhak6prjE1RBCnYDKZEgpdg==,iv:k4/WP2toLLU6tBCjvsoBpeFv+FVl7cmObNsTvZdR0fo=,tag:ivST8TFEy9Nb6SysjZ5yBQ==,type:str]
MONGO_INITDB_DATABASE: ENC[AES256_GCM,data:SH5LkPp3,iv:cFlrAuvAmHs6bCHArhl4TW5kXiKxQJMw7e2PSCqMfmo=,tag:HJ+qlu+LzyK4Uo9kMQLGlg==,type:str]
MINIO_ROOT_USER: ENC[AES256_GCM,data:2+wWSnkfw6Qox6vSvbIrcPQ=,iv:boiNo9npw/d3Epocq+cw3wySwsng2IaPRyOckUhevlg=,tag:54ZFhCiggVSn4HaW3ppKHQ==,type:str]
MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:5MxZD5pUcpAvKZHxL7/mo3UA9g==,iv:CWyZeEV9etc903UAOaT2y8OsNhMOEVp/Yd0HECFKffc=,tag:s+ubUamA6moTXk6qpq49gg==,type:str]
DB_NAME: ENC[AES256_GCM,data:5UI8OWjI,iv:ABnGSGjtD8u57Z+eRJofC6v7tpdEoaG8D37w5ieptSo=,tag:9ikALXEb0OCWQE3nEG1Few==,type:str]
DB_USER: ENC[AES256_GCM,data:lUmmhfLswQp5crWMCPIO,iv:WryzDt1z/5rmhbYURpy5GXk75THTILvS8bM3h6uK3/o=,tag:57FXS4axn0z8pBCoUVvQFQ==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:lx1ik53r/eZzJSB+e31/Ow==,iv:sAQkoFbUtiQEUbP/Oaj78rZpM5Bu04FvC/eE1ojQovc=,tag:yHLP9MQRYLPRYx1m3LuJHQ==,type:str]
#ENC[AES256_GCM,data:L/Jz7E2fic+i31uxINbF2zcwIVi7cYZXFRLpoJx4yeSv8a71b3iq5q4a,iv:+b+rM0OiE8JjyOfYzWkhLn4bI6dk8boa81WnYLkGwC4=,tag:zs+gTGo9MvinA5FjKqvDKA==,type:comment]
ELASTICSEARCH_URL: ENC[AES256_GCM,data:ZyTrep10thoORWBVRYGajlSGwhe2ZHhMFQ==,iv:NIy1i0JPc0wsrN8pc8QIsvt/kj9BGcV9lScVmrZ60p8=,tag:XTUX0ePbxDLE2isz1ExtJg==,type:str]
MONGO_URL: ENC[AES256_GCM,data:0cGw/Mm1ak/IkXElcqH//rBEnovzN4a4yDPmMbkY/SNTYnopvx11MM5hOqhU9ZAFUnv5yeF3kNa0+jt2FdgQ44DEl2kWCeuwCCkfX/Aidd75,iv:SWF9ymgVnztLzy7aX570B5gIjYNiCT5hbLEwQeAGAJQ=,tag:i6I3dmUN1NPMvp5IFZ4eaw==,type:str]
POSTGRES_DSN: ENC[AES256_GCM,data:jtr9MrENL5ttoXRrjIsRkmpCefreOOem6hYGbvRVF6joi5AF9TvXPqnO/CMNtINEjw1JvR/vCjMP4J0dBWhXrddssp5G4dMk/hSPlwss5Hk=,iv:Yk6cZ9aRgu5o61+zpXWDwbKGIRq1dn/lZJNFNCa5EGM=,tag:BsjaBdoWZJK7uOJIiTNIqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVGtnVjVZUEJUS1hZOG9m
            Vlp5TU9PUi8xaWhPZUZMKytHQ3A0QlZTVFJJCkZCVEFvYzlvOEVXdDVSQUlMcmRu
            ZHYwU2ZrM1ZsWjdTNnZMOEd6VWgwV1EKLS0tIElPZWNidnpoOGlxOTJJeVpLTk5F
            RS9yVUJmTXMzV0dteEFhcjJYUUJrNEUKWzKraglY9hmUVKXXTZg2K5z/WXMwIJBA
            zrshzRRXZYYZ7GMeBFfjeLI3xEfHR0053KhikYdlo8g+KVVLsT/GKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqgm0gczrwyluk9lyhpz49uea7m04u53q4c60kwn9s6wuguhju3qjznrut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcXpEVHF4MGRaVHZ1UnRx
            UGcyKzVhQm1IV1ZNajdKeTNXelJXbktuWGlJCkFnUHNXayszejZNc1o5djFlK2lM
            ZW5WYTdyNlZ4MjlsWkFNeXROcmZNRjgKLS0tIFJSUFA2TFF2L242ZFFsWEFpcThE
            TjB6ekR4L3RWR2o2UjlBdWQ4S3Z6UlUKvDbsvUjYzGaS4u/QAUQl3Ogm2KQ6ZWNU
            gqePqIIZKBhljdDCb6Go2KoaIF9R5qNpELAJIWhDrrmnhPvGpJ3WSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T17:45:20Z"
    mac: ENC[AES256_GCM,data:QYwvKF6x1QbycXWkPVC4j8JrwCq+ZT7AewPKHhgUcqV4V2PLJpXvJC+prXJvpJYTV3G0JwxCpWpndU4OZWYJXo0qHP1TKDvtbSClfG8fvvdUpcgOT7hsX1DM0aXUhEqloeAa0zTAEvPUcGOuu0/3tP2sj0apJ0CK0rAYH9xpECs=,iv:Bv/s820mPmffPKRc7NZ238Wt436CrZOsXXBZ2v7o99M=,tag:QHyy4/biMx0KHOh8G0Y5hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
