apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: pechka
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: <path:secrets/prod-secrets.yaml#MONGO_INITDB_ROOT_USERNAME>
  MONGO_INITDB_ROOT_PASSWORD: <path:secrets/prod-secrets.yaml#MONGO_INITDB_ROOT_PASSWORD>
  MONGO_INITDB_DATABASE: <path:secrets/prod-secrets.yaml#MONGO_INITDB_DATABASE>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pechka
type: Opaque
stringData:
  POSTGRES_USER: <path:secrets/prod-secrets.yaml#DB_USER>
  POSTGRES_PASSWORD: <path:secrets/prod-secrets.yaml#DB_PASSWORD>
  POSTGRES_DB: <path:secrets/prod-secrets.yaml#DB_NAME>
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: pechka
type: Opaque
stringData:
  MINIO_ROOT_USER: <path:secrets/prod-secrets.yaml#MINIO_ROOT_USER>
  MINIO_ROOT_PASSWORD: <path:secrets/prod-secrets.yaml#MINIO_ROOT_PASSWORD>
