apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: pechka
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: <path:secrets/prod-secrets.yaml#MONGO_INITDB_ROOT_USERNAME>
  MONGO_INITDB_ROOT_PASSWORD: <path:secrets/prod-secrets.yaml#MONGO_INITDB_ROOT_PASSWORD>
  MONGO_INITDB_DATABASE: <path:secrets/prod-secrets.yaml#MONGO_INITDB_DATABASE>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pechka
type: Opaque
stringData:
  DB_HOST: postgres
  DB_NAME: <path:secrets/prod-secrets.yaml#DB_NAME>
  DB_USER: <path:secrets/prod-secrets.yaml#DB_USER>
  DB_PASSWORD: <path:secrets/prod-secrets.yaml#DB_PASSWORD>
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: pechka
type: Opaque
stringData:
  MINIO_ROOT_USER: <path:secrets/prod-secrets.yaml#MINIO_ROOT_USER>
  MINIO_ROOT_PASSWORD: <path:secrets/prod-secrets.yaml#MINIO_ROOT_PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: benthos-secret
  namespace: pechka
type: Opaque
stringData:
  POSTGRES_DSN: <path:secrets/prod-secrets.yaml#POSTGRES_DSN>
  MONGO_URL: <path:secrets/prod-secrets.yaml#MONGO_URL>
  ELASTICSEARCH_URL: <path:secrets/prod-secrets.yaml#ELASTICSEARCH_URL>
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: pechka
type: Opaque
stringData:
  POSTGRES_DSN: <path:secrets/prod-secrets.yaml#POSTGRES_DSN>
  MONGO_URL: <path:secrets/prod-secrets.yaml#MONGO_URL>
  ELASTICSEARCH_URL: <path:secrets/prod-secrets.yaml#ELASTICSEARCH_URL>
---
apiVersion: v1
kind: Secret
metadata:
  name: pechka-minio
  namespace: pechka
type: Opaque
stringData:
  access-key: <path:secrets/prod-secrets.yaml#MINIO_ROOT_USER>
  secret-key: <path:secrets/prod-secrets.yaml#MINIO_ROOT_PASSWORD>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: pechka
type: Opaque
stringData:
  user: <path:secrets/prod-secrets.yaml#DB_USER>
  password: <path:secrets/prod-secrets.yaml#DB_PASSWORD>
  database: <path:secrets/prod-secrets.yaml#DB_NAME>
---
apiVersion: v1
kind: Secret
metadata:
  name: pechka-postgres
  namespace: pechka
type: Opaque
stringData:
  dsn: <path:secrets/prod-secrets.yaml#POSTGRES_DSN>
