resources:
- ../../base
- ../../infra
- nfs-pv.yaml
- dev-proxy.yaml

patches:
- path: patches/frontend-exposure.yaml
- path: patches/nfs-data.yaml
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent
- target:
    kind: CronJob
  patch: |-
    - op: add
      path: /spec/jobTemplate/spec/template/spec/containers/0/imagePullPolicy
      value: IfNotPresent

images:
- name: pechka-app
  newName: pechka-app
  newTag: latest
- name: pechka-ffmpeg
  newName: pechka-ffmpeg
  newTag: latest
- name: pechka-analyzer
  newName: pechka-analyzer
  newTag: latest
- name: pechka-frontend
  newName: pechka-frontend
  newTag: latest
