apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/nfs
    type: Directory
  storageClassName: manual
