apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-api
  namespace: pechka
  labels:
    app: file-server-api
spec:
  selector:
    matchLabels:
      app: file-server-api
  template:
    metadata:
      labels:
        app: file-server-api
    spec:
      containers:
        - name: file-server-api
          image: ghcr.io/k-wa-wa/pechka-file-server-api
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: mnt-hls
              mountPath: "/mnt/hls"
          env:
            - name: HLS_RESOURCE_DIR
              value: /mnt/hls
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
                  optional: false
            - name: DB_NAME
              value: pechka
            - name: SSL_MODE
              value: disable
      volumes:
        - name: mnt-hls
          persistentVolumeClaim:
            claimName: nfs-hls-readonly-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: file-server-api
  namespace: pechka
spec:
  selector:
    app: file-server-api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
