FROM golang:1.24.2-bookworm AS builder

WORKDIR /app
ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd/
COPY pkg/ ./pkg/
COPY internal/ ./internal/

RUN go build -o bin ./cmd/transform-mkv


FROM linuxserver/ffmpeg:version-7.1-cli AS runner

WORKDIR /app
COPY --from=builder /app/bin .

ENTRYPOINT [ "/app/bin" ]
