apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pechka

resources:
  - extract-job.yaml
  - transcode-job.yaml
  - load-job.yaml
  - refresh-latest-playlist-job.yaml
  - thumbnail-job.yaml
