apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: etl-bluray-manual-
  namespace: pechka
spec:
  workflowTemplateRef:
    name: etl-bluray
  entrypoint: manual
  arguments:
    parameters:
      - name: db-host
        value: postgres
      - name: disc-label
        value: TEST_DISC_001
      - name: content-title
        value: "サンプル動画コンテンツ"
