apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-bluray-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-bluray-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-hls-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-hls-readonly-pvc
  namespace: pechka
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-hls-readonly-pv
