apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: pechka
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: pechka
  MONGO_INITDB_ROOT_PASSWORD: changeme
  MONGO_INITDB_DATABASE: pechka
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pechka
type: Opaque
stringData:
  POSTGRES_USER: pechka
  POSTGRES_PASSWORD: changeme
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: pechka
type: Opaque
stringData:
  MINIO_ROOT_USER: pechka
  MINIO_ROOT_PASSWORD: changeme_minio
---
apiVersion: v1
kind: Secret
metadata:
  name: benthos-secret
  namespace: pechka
type: Opaque
stringData:
  POSTGRES_DSN: "postgres://pechka:changeme@postgres:5432/pechka?sslmode=disable"
  MONGO_URL: "mongodb://pechka:changeme@mongodb:27017/pechka?authSource=admin"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: pechka
type: Opaque
stringData:
  POSTGRES_DSN: "postgres://pechka:changeme@postgres:5432/pechka?sslmode=disable"
  MONGO_URL: "mongodb://pechka:changeme@mongodb:27017/pechka?authSource=admin"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: pechka
type: Opaque
stringData:
  ADMIN_PASSWORD: changeme_grafana
