name: api-prototype workflow

on:
  push:
    branches:
      - master
    paths:
      - api/prototype/*

defaults:
      run:
        working-directory: api/prototype

jobs:
  publish_docker_image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/pechka-api-prototype:latest \
          --tag ghcr.io/$GITHUB_ACTOR/pechka-api-prototype:$(echo $GITHUB_SHA | head -c7) \
          .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/pechka-api-prototype:latest
          docker push ghcr.io/$GITHUB_ACTOR/pechka-api-prototype:$(echo $GITHUB_SHA | head -c7)
