name: Docker Build and Push

on:
  push:
    branches:
      - master
    paths:
      - home-automation/ble-metrics/**/*

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/k-wa-wa/home-automation-ble-metrics
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: home-automation/ble-metrics
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}

