DB_NAME: ENC[AES256_GCM,data:ASSCRz/Z,iv:PYAqpQlh+puI0K9U/G0QdTC2n32pI7ovsUdtclR8YjE=,tag:x/e1rZ5IHsqQ4+yIbV43bg==,type:str]
DB_USER: ENC[AES256_GCM,data:5UmippWwicFG/dRttG+M,iv:VHlvXPw8eqwIDjqlfIkI0+2iYU97Nz7VClqJzcMTiMw=,tag:9vEoImcM4zPiGmcNL63Rsw==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:Mhr6mbSJAq+jFIVPzfAeDg==,iv:R+CSe17VTruuKA+JEd/SlajOD29YlinQX/jKSDpJENk=,tag:fZmgtIN1E6tIerT3QN/32g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17e67u5g3j9v6sxxrk448gsgmv9ldc2umqgad579du75fgjkjtcasatrhxr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbDNCVXlsZy9OdTNRVUc2
            Ri9qU29keXQxcXh0UThRc3g5aWYwb0JnWVd3CmVGV2sxczQ3N2V5V2R1dmtoZlNO
            UWxhd2Z3NFUzSFpsOXRKRDZPWFhzYTQKLS0tIGdvUkJURXBNc0tGVkV0NEdXbFMv
            V1kxOHpYVS9HQnBldEt6cjUwQzZERzgKVYcrXn0xNL9uuSN4LYn5d7s7OXTaOKIn
            BlL3QZIIy/d7L1o+AcdxCWwZRw7TW+BXqj8On5K4pRFzR352pAMIgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqgm0gczrwyluk9lyhpz49uea7m04u53q4c60kwn9s6wuguhju3qjznrut
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVFdSMnpNME9RWExTVXhv
            MWZOU045c21zL2VwQ1JDdlpFSFRrdnd5TWxjCi9rL1NxZUUvcy9uUHpDQkdTM1Rj
            TXlJWHlWOC8yaTNPMXhpMUw1STQ2VVkKLS0tIDNodjBjRlRFRUNZQzEyUVJZSWli
            MkFNWnNrOGl2ZU93eTBYQitjbUhiS2sKvzp4EPyU9BAIT0vtUZA+z6SgGext9ZGE
            xbj0+h2qn3JDTSwJFTsAh1JdziagrNCXn4vd3V767DOqqJN/pLR9GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-17T19:05:28Z"
    mac: ENC[AES256_GCM,data:GIkF52f7kYld6ZsqtMCzKsB2ipwbJqfHbdw+TEo1OUbH7wcbTlRkZ2wZXY653Y/4YaZ0SVwIjEvBZ2n20U60a4iXSgAy53agoGScq7lvgedHDv9D4a/MnDwzcz201/+vrtp0Vfc4wqycSGZE7xJHor290scZmu5Sur2y2uL7Bm8=,iv:juBD9/poERoYSZ/wqhfBMJgOmx4PkMkH3jiRpdocpSs=,tag:WMlquR6xjKpW9OYlxgsl2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
